# Goal
float32 angle_x
float32 angle_y
float32 angle
float32 pixel_dist
---
# Result
bool success
string message
---
# Feedback
float32 current_error_x
float32 current_error_y
float32 current_error_z
