# Goal
float32 forward       #正为前进，负为后退（单位：米）
float32 right         #正为右移，负为左移
float32 up            #正为上升，负为下降
float32 angle         #角度

---
# Result
bool success
string message

---
# Feedback
float32 traveled_distance
