movement:
  #水平距离阈值
  hor_th: 0.9
  #垂直距离阈值
  ver_th: 0.4
  #飞行阈值
  delta: 0.6

track:
  #yaw PID
  yaw_kp: 0.00003
  yaw_ki: 0.00001
  yaw_kd: 0.0
  yaw_th: 0.7
  #上下 PID
  ud_kp: 0.002
  ud_ki: 0.00001
  ud_kd: 0.0
  ud_th: 0.7
  #前后 PID
  fb_kp: 0.000003
  fb_ki: 0.00001
  fb_kd: 0.0
  fb_th: 0.7
  #跟踪面积
  area_th: 0.41

#跟踪
visual_track:
  #飞行高度
  lift_height: 1.5
  #dt时间间隔
  dt: 10
  #是否室外
  outdoor_flag: true
  #是否切换速度模式
  switch_mode: false
  #是否使用loc位置
  is_loc_pos: false
  #是否等待视觉
  is_wait_vision: false
  # 是否室内模拟
  is_indoor_sim: false
  # 运动方位: 左右、上下、前后
  is_enable_dir: [true, false, true]
  # 是否跟踪
  is_track: false
  # 是否等待10s切换模式
  is_wait_10s: true