topic_out:
  PX4_MODE:                 "/control/out/offboard_mode"
  TRACKING_FEEDBACK:        "/vision_pipeline/tracking_feedback"
  YOLO_DETECTIONS:          "/yolo_detections"

topic_in:
  PX4_MODE:                 "/control/in/offboard_mode"

topic_px4_in:
  VEHICLE_COMMAND:          "/fmu/in/vehicle_command"
  OFFBOARD_CONTROL_MODE:    "/fmu/in/offboard_control_mode"
  PX4_TRAJECTORY_SETPOINT:  "/fmu/in/trajectory_setpoint"
  MISSION:                  "/fmu/in/mission"
  NAVIGATOR_MISSION_ITEM:   "/fmu/in/navigator_mission_item"

topic_px4_out:
  VEHICLE_STATUS:           "/fmu/out/vehicle_status_v1"
  VEHICLE_LOCAL_POSITION:   "/fmu/out/vehicle_local_position_v1"
  VEHICLE_ODOMETRY:         "/fmu/out/vehicle_odometry"
  VEHICLE_GLOBAL_POSITION:  "/fmu/out/vehicle_global_position"
  BATTERY_STATUS:           "/fmu/out/battery_status"
  VEHICLE_ATTITUDE:         "/fmu/out/battery_status"
  VEHICLE_ATTITUDE_V:       "/fmu/out/vehicle_angular_velocity"
  SENSOR_COMBINED:          "/fmu/out/sensor_combined"
  MANUAL_CONTROL_SETPOINT:  "/fmu/out/manual_control_setpoint"
